### ISSUE TITLE
@posthog/nextjs-config breaks my build on vercel

### ISSUE THREAD

**Issue by harrisrobin** [PostHog/posthog-js-lite#562]
A partial log screenshot is here: <https://share.cleanshot.com/vhZvzg01>

---

## How to reproduce

1. In a Next.js project (monorepo or standalone), install and configure **`posthog-nextjs-config`** as per the docs.  
2. Set the required PostHog environment variables (`POSTHOG_API_KEY`, `POSTHOG_PROJECT_ID`, `POSTHOG_ENV_ID` etc.) in Vercel.  
3. Push to Vercel; the build breaks during the PostHog sourcemap upload step with the errors above.

---

## Related sub-libraries

- [ ] All of them  
- [ ] posthog-web  
- [ ] posthog-node  
- [ ] posthog-ai  
- [ ] posthog-react-native  
- [x] posthog-nextjs-config  

---

## Additional context
- Next.js version: 15.3.4
- Build platform: Vercel  
- Repo structure: `/apps/web` path shown in logs  
- Screenshot with full stack trace: <https://share.cleanshot.com/vhZvzg01>

**Comment by liamross** [comment]
I get an issue as well, but slightly different. First off I'm on `pnpm` and using canary `116` of next.

First, the post install of post hog CLI:

<img width="1021" height="134" alt="Image" src="https://github.com/user-attachments/assets/69e2ca5b-c109-4d5e-bb2e-b17ea929cc94" />

Then, the error later on:

`Error running PostHog sourcemap plugin: spawn posthog-cli ENOENT`

**Comment by hpouillot** [comment]
Thanks for reporting this issue ! It should be fixed with version 1.0.2

**Comment by harrisrobin** [comment]
@hpouillot thanks. That seems to have fixed the above error but unfortunately i still face an issue.

here's the new errro:

```
web:build: 2025-07-13T00:32:48.737403Z  INFO posthog_cli::utils::sourcemaps: Processing file: /vercel/path0/apps/web/.next/static/chunks/12e8a754.5797c2f1a2fb360b.js
web:build: 2025-07-13T00:32:48.738049Z  WARN posthog_cli::utils::sourcemaps: No sourcemap file found for file /vercel/path0/apps/web/.next/static/chunks/12e8a754.5797c2f1a2fb360b.js
web:build: 2025-07-13T00:32:48.738120Z  INFO posthog_cli::utils::sourcemaps: Processing file: /vercel/path0/apps/web/.next/static/chunks/856e791d.d7b2c4e9b49cb322.js
web:build: 2025-07-13T00:32:48.738236Z  WARN posthog_cli::utils::sourcemaps: No sourcemap file found for file /vercel/path0/apps/web/.next/static/chunks/856e791d.d7b2c4e9b49cb322.js
web:build: 2025-07-13T00:32:48.738263Z  INFO posthog_cli::utils::sourcemaps: Processing file: /vercel/path0/apps/web/.next/static/chunks/66.eca4dac61c4ddd7f.js
web:build: 2025-07-13T00:32:48.738300Z  WARN posthog_cli::utils::sourcemaps: No sourcemap file found for file /vercel/path0/apps/web/.next/static/chunks/66.eca4dac61c4ddd7f.js
web:build: 2025-07-13T00:32:48.738323Z  INFO posthog_cli::utils::sourcemaps: Processing file: /vercel/path0/apps/web/.next/static/chunks/6315.af6f973cb7f93c10.js
web:build: 2025-07-13T00:32:48.738518Z  WARN posthog_cli::utils::sourcemaps: No sourcemap file found for file /vercel/path0/apps/web/.next/static/chunks/6315.af6f973cb7f93c10.js
web:build: 2025-07-13T00:32:48.738568Z ERROR posthog_cli: msg="Oops! No source files found"
web:build: Error running PostHog sourcemap plugin: Command failed with code 1
  Tasks:    1 successful, 1 total
 Cached:    0 cached, 1 total
   Time:    4m14.126s 
Summary:    /vercel/path0/.turbo/runs/2znVLgQQX6WekQDLVrh6qfl4iLF.json
Error: The file "/vercel/path0/apps/web/.next/routes-manifest.json" couldn't be found. This is often caused by a misconfiguration in your project.
Learn More: https://err.sh/vercel/vercel/now-next-routes-manifest
Exiting build container
```

**Comment by hpouillot** [comment]
@harrisrobin could you share you next config ? Also, did you set /apps/web as the root directory on vercel ?

**Comment by liamross** [comment]
This fixed my issue! Thanks. (Fixed by release 1.0.2)
